import { type NextPage } from "next";
import Head from "next/head";
import ChatList from "@/components/chat/ChatList";
import AuthShowcase from "@/components/auth/AuthShowcase";
import ChatsHeader from "@/components/chat/ChatsHeader";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>T3 Chat App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <main className="container mx-auto h-max max-w-screen-md px-4 py-20 lg:px-0">
        <h1 className="text-4xl font-extrabold tracking-tight text-gray-800 sm:text-6xl">
          <span className="text-emerald-700">T3</span> Chat App
        </h1>
        <AuthShowcase />
        <ChatsHeader />
        <ChatList />
      </main>
    </>
  );
};

export default Home;
